### ISSUE TITLE
Not working in latest version of burp

### ISSUE THREAD

**Issue by vulnh0lich2** [nccgroup/AutoRepeater#55] opened 2019-10-03 18:45 UTC

**Comment by dokkillo** [comment] 2019-11-11 09:35
yes, its true, dont work.
I try to add requests to autorepeater and nothing happen

**Comment by justinmoore** [comment] 2019-11-11 18:20
Hey folks,

I downloaded the newest version of burp and AutoRepeater does appear to be working as intended. You can try by setting a string replacement for google and replacing it with test and then loading google.com.

Thanks,
Justin

**Comment by dokkillo** [comment] 2019-11-13 16:25
Justinmoore you are true, its working! ty!

**Comment by justinmoore** [comment] 2019-11-14 02:52
That’s great to hear. I’m going to close this issue out. If it pops back up for persists feel free to reopen it.

Thanks,
Justin

**Closed by justinmoore** 2019-11-14 02:52 UTC

**Comment by vdb-sander** [comment] 2019-12-09 09:24
Autorepeater doesn't work in Burp Professional v2.1.04
