### ISSUE TITLE
Log Filter maybe stuck

### ISSUE THREAD

**Issue by LandGrey** [nccgroup/AutoRepeater#48] opened 2019-01-13 15:36 UTC
As following picture, when i used AutoPrepeater for a while, the Log Filter Frame maybe stuck and Freezes.
I just look some sites and loged about 100-150 items ……
and I used the lastest version AutoRepeater.jar .

![image](https://user-images.githubusercontent.com/16769779/51086734-393e8a80-1785-11e9-914c-158e76842955.png)

Also lead to whole burpsuite stuck
![image](https://user-images.githubusercontent.com/16769779/51087338-f7b1dd80-178c-11e9-86be-5da1da4b3350.png)

here is configure: 
```
[{
	"isActivated": true,
	"isWhitelistFilter": true,
	"baseReplacements": [{
		"type": "Request String",
		"match": "a",
		"replace": "b",
		"comment": "",
		"which": "Replace First",
		"isRegexMatch": false,
		"isEnabled": true
	},
	{
		"type": "Request Header",
		"match": "User-Agent:.*?",
		"replace": "User-Agent: jalsdjfouaosdf",
		"comment": "",
		"which": "Replace First",
		"isRegexMatch": true,
		"isEnabled": true
	}],
	"replacements": [{
		"type": "Request Header",
		"match": "User-Agent:.*?",
		"replace": "User-Agent: () {:;};ping -nc 1 test.me\"",
		"comment": "",
		"which": "Replace First",
		"isRegexMatch": true,
		"isEnabled": true
	},
	{
		"type": "Request Header",
		"match": "User-Aget:.*?",
		"replace": "User-Agent: testss",
		"comment": "",
		"which": "Replace All",
		"isRegexMatch": true,
		"isEnabled": true
	}],
	"conditions": [{
		"booleanOperator": "",
		"matchType": "Sent From Tool",
		"matchRelationship": "Burp",
		"matchCondition": "",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "jpg",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "js",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "png",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "gif",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "css",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "jpeg",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": "svg",
		"isEnabled": true
	},
	{
		"booleanOperator": "And",
		"matchType": "File Extension",
		"matchRelationship": "Does Not Match",
		"matchCondition": ".ico",
		"isEnabled": true
	}],
	"filters": [{
		"originalOrModified": "Original",
		"booleanOperator": "",
		"matchType": "Sent From Tool",
		"matchRelationship": "Burp",
		"matchCondition": "",
		"isEnabled": true
	}],
	"highlighters": [],
	"tabName": "1"
}]
```

**Comment by justinmoore-ncc** [comment] 2019-01-14 19:32
Hey @LandGrey,

Thanks for the bug report, it looks like there was an unhandled exception which caused everything to go wonky. By chance were you sorting the log results?

Thanks,
Justin

**Comment by LandGrey** [comment] 2019-01-15 02:10
I didn't sorting the log results, until the log results seems to much to be stucked.

**Comment by LandGrey** [comment] 2019-01-18 02:09
Sorry for my first replies.
I test again and found the log filter stucked only I sorted the log results.
I noticed the [issues#46](https://github.com/nccgroup/AutoRepeater/issues/46)
that's a unfix bug?

**Comment by justinmoore-ncc** [comment] 2019-01-21 18:54
#46 should be fixed in the newest JAR, i just haven't closed the issue. Does the issue persist?

**Comment by LandGrey** [comment] 2019-01-22 09:47
yeah, the issue exists, when I sorted the log results, the log filter will be stucked.

**Comment by justinmoore** [comment] 2019-02-01 16:16
Hey @LandGrey,

#46 was a different issue causing Burp to crash when logs where cleared that has been resolved. This issue currently exists. 

Thanks,
Justin

**Comment by arbazkiraak** [comment] 2019-02-03 11:34
Hi @justinmoore 

I Confirmed the same, Issue is with sorting log. 

![bug](https://user-images.githubusercontent.com/13177578/52176208-7ec70400-27d5-11e9-910c-92d3593bb014.PNG)

Have you figure out a way to fix this ?

**Comment by justinmoore** [comment] 2019-02-04 20:34
hey @arbazkiraak,

I was able to fix this bug. The issue should no longer exist in the newest JAR. If it does please reopen this issue and i'll look into it again.

Thanks,
Justin

**Closed by justinmoore** 2019-02-04 20:34 UTC
